### ISSUE TITLE
没有处理图片的脚本哎

### ISSUE THREAD

**Issue by YujieShui** [longpeng2008/yousan.ai#1]
https://github.com/longpeng2008/yousan.ai/tree/master/computer_vision/datas/mouth

> (2) 脚本介绍
script中包含若干脚本
-reformat.py 批量修改图片格式
-checksize.py 批量查看图片大小
-genelist.py 从文件夹中生成分类格式的list
-gene_train_val.py 将图片按照一定比例分为train和val
-shuffle.py 用于随机打乱图片list
-rename_files_function,run_rename.sh 批量重命名图片，用于统一格式

没有`script`文件夹哎

**Comment by Tanapl02** [comment]
Open
